// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextReferrer (
  val url: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextReferrer {
      val url = pigeonVar_list[0] as String?
      return NativeContextReferrer(url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContext (
  val app: NativeContextApp? = null,
  val device: NativeContextDevice? = null,
  val library: NativeContextLibrary? = null,
  val locale: String? = null,
  val network: NativeContextNetwork? = null,
  val os: NativeContextOS? = null,
  val screen: NativeContextScreen? = null,
  val timezone: String? = null,
  val userAgent: String? = null,
  val referrer: NativeContextReferrer? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContext {
      val app = pigeonVar_list[0] as NativeContextApp?
      val device = pigeonVar_list[1] as NativeContextDevice?
      val library = pigeonVar_list[2] as NativeContextLibrary?
      val locale = pigeonVar_list[3] as String?
      val network = pigeonVar_list[4] as NativeContextNetwork?
      val os = pigeonVar_list[5] as NativeContextOS?
      val screen = pigeonVar_list[6] as NativeContextScreen?
      val timezone = pigeonVar_list[7] as String?
      val userAgent = pigeonVar_list[8] as String?
      val referrer = pigeonVar_list[9] as NativeContextReferrer?
      return NativeContext(app, device, library, locale, network, os, screen, timezone, userAgent, referrer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      app,
      device,
      library,
      locale,
      network,
      os,
      screen,
      timezone,
      userAgent,
      referrer,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextApp (
  val build: String? = null,
  val name: String? = null,
  val namespace: String? = null,
  val version: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextApp {
      val build = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val namespace = pigeonVar_list[2] as String?
      val version = pigeonVar_list[3] as String?
      return NativeContextApp(build, name, namespace, version)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      build,
      name,
      namespace,
      version,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextDevice (
  val id: String? = null,
  val manufacturer: String? = null,
  val model: String? = null,
  val name: String? = null,
  val type: String? = null,
  val adTrackingEnabled: Boolean? = null,
  val advertisingId: String? = null,
  val trackingStatus: String? = null,
  val token: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextDevice {
      val id = pigeonVar_list[0] as String?
      val manufacturer = pigeonVar_list[1] as String?
      val model = pigeonVar_list[2] as String?
      val name = pigeonVar_list[3] as String?
      val type = pigeonVar_list[4] as String?
      val adTrackingEnabled = pigeonVar_list[5] as Boolean?
      val advertisingId = pigeonVar_list[6] as String?
      val trackingStatus = pigeonVar_list[7] as String?
      val token = pigeonVar_list[8] as String?
      return NativeContextDevice(id, manufacturer, model, name, type, adTrackingEnabled, advertisingId, trackingStatus, token)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      manufacturer,
      model,
      name,
      type,
      adTrackingEnabled,
      advertisingId,
      trackingStatus,
      token,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextLibrary (
  val name: String? = null,
  val version: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextLibrary {
      val name = pigeonVar_list[0] as String?
      val version = pigeonVar_list[1] as String?
      return NativeContextLibrary(name, version)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      version,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextOS (
  val name: String? = null,
  val version: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextOS {
      val name = pigeonVar_list[0] as String?
      val version = pigeonVar_list[1] as String?
      return NativeContextOS(name, version)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      version,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextNetwork (
  val cellular: Boolean? = null,
  val wifi: Boolean? = null,
  val bluetooth: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextNetwork {
      val cellular = pigeonVar_list[0] as Boolean?
      val wifi = pigeonVar_list[1] as Boolean?
      val bluetooth = pigeonVar_list[2] as Boolean?
      return NativeContextNetwork(cellular, wifi, bluetooth)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cellular,
      wifi,
      bluetooth,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeContextScreen (
  val height: Long? = null,
  val width: Long? = null,
  val density: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeContextScreen {
      val height = pigeonVar_list[0] as Long?
      val width = pigeonVar_list[1] as Long?
      val density = pigeonVar_list[2] as Double?
      return NativeContextScreen(height, width, density)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      height,
      width,
      density,
    )
  }
}
private open class ContextPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextReferrer.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContext.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextApp.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextDevice.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextLibrary.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextOS.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextNetwork.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeContextScreen.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeContextReferrer -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeContext -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeContextApp -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeContextDevice -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeContextLibrary -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeContextOS -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeContextNetwork -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeContextScreen -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeContextApi {
  fun getContext(collectDeviceId: Boolean, callback: (Result<NativeContext>) -> Unit)
  fun clearReferrer()

  companion object {
    /** The codec used by NativeContextApi. */
    val codec: MessageCodec<Any?> by lazy {
      ContextPigeonCodec()
    }
    /** Sets up an instance of `NativeContextApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeContextApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.segment_analytics.NativeContextApi.getContext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val collectDeviceIdArg = args[0] as Boolean
            api.getContext(collectDeviceIdArg) { result: Result<NativeContext> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.segment_analytics.NativeContextApi.clearReferrer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearReferrer()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
