// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextReferrer {
  var url: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextReferrer? {
    let url: String? = nilOrValue(pigeonVar_list[0])

    return NativeContextReferrer(
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      url
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContext {
  var app: NativeContextApp? = nil
  var device: NativeContextDevice? = nil
  var library: NativeContextLibrary? = nil
  var locale: String? = nil
  var network: NativeContextNetwork? = nil
  var os: NativeContextOS? = nil
  var screen: NativeContextScreen? = nil
  var timezone: String? = nil
  var userAgent: String? = nil
  var referrer: NativeContextReferrer? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContext? {
    let app: NativeContextApp? = nilOrValue(pigeonVar_list[0])
    let device: NativeContextDevice? = nilOrValue(pigeonVar_list[1])
    let library: NativeContextLibrary? = nilOrValue(pigeonVar_list[2])
    let locale: String? = nilOrValue(pigeonVar_list[3])
    let network: NativeContextNetwork? = nilOrValue(pigeonVar_list[4])
    let os: NativeContextOS? = nilOrValue(pigeonVar_list[5])
    let screen: NativeContextScreen? = nilOrValue(pigeonVar_list[6])
    let timezone: String? = nilOrValue(pigeonVar_list[7])
    let userAgent: String? = nilOrValue(pigeonVar_list[8])
    let referrer: NativeContextReferrer? = nilOrValue(pigeonVar_list[9])

    return NativeContext(
      app: app,
      device: device,
      library: library,
      locale: locale,
      network: network,
      os: os,
      screen: screen,
      timezone: timezone,
      userAgent: userAgent,
      referrer: referrer
    )
  }
  func toList() -> [Any?] {
    return [
      app,
      device,
      library,
      locale,
      network,
      os,
      screen,
      timezone,
      userAgent,
      referrer,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextApp {
  var build: String? = nil
  var name: String? = nil
  var namespace: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextApp? {
    let build: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let namespace: String? = nilOrValue(pigeonVar_list[2])
    let version: String? = nilOrValue(pigeonVar_list[3])

    return NativeContextApp(
      build: build,
      name: name,
      namespace: namespace,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      build,
      name,
      namespace,
      version,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextDevice {
  var id: String? = nil
  var manufacturer: String? = nil
  var model: String? = nil
  var name: String? = nil
  var type: String? = nil
  var adTrackingEnabled: Bool? = nil
  var advertisingId: String? = nil
  var trackingStatus: String? = nil
  var token: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextDevice? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let manufacturer: String? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])
    let name: String? = nilOrValue(pigeonVar_list[3])
    let type: String? = nilOrValue(pigeonVar_list[4])
    let adTrackingEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let advertisingId: String? = nilOrValue(pigeonVar_list[6])
    let trackingStatus: String? = nilOrValue(pigeonVar_list[7])
    let token: String? = nilOrValue(pigeonVar_list[8])

    return NativeContextDevice(
      id: id,
      manufacturer: manufacturer,
      model: model,
      name: name,
      type: type,
      adTrackingEnabled: adTrackingEnabled,
      advertisingId: advertisingId,
      trackingStatus: trackingStatus,
      token: token
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      manufacturer,
      model,
      name,
      type,
      adTrackingEnabled,
      advertisingId,
      trackingStatus,
      token,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextLibrary {
  var name: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextLibrary? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let version: String? = nilOrValue(pigeonVar_list[1])

    return NativeContextLibrary(
      name: name,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      version,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextOS {
  var name: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextOS? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let version: String? = nilOrValue(pigeonVar_list[1])

    return NativeContextOS(
      name: name,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      version,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextNetwork {
  var cellular: Bool? = nil
  var wifi: Bool? = nil
  var bluetooth: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextNetwork? {
    let cellular: Bool? = nilOrValue(pigeonVar_list[0])
    let wifi: Bool? = nilOrValue(pigeonVar_list[1])
    let bluetooth: Bool? = nilOrValue(pigeonVar_list[2])

    return NativeContextNetwork(
      cellular: cellular,
      wifi: wifi,
      bluetooth: bluetooth
    )
  }
  func toList() -> [Any?] {
    return [
      cellular,
      wifi,
      bluetooth,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextScreen {
  var height: Int64? = nil
  var width: Int64? = nil
  var density: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextScreen? {
    let height: Int64? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let density: Double? = nilOrValue(pigeonVar_list[2])

    return NativeContextScreen(
      height: height,
      width: width,
      density: density
    )
  }
  func toList() -> [Any?] {
    return [
      height,
      width,
      density,
    ]
  }
}

private class ContextPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeContextReferrer.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeContext.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeContextApp.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeContextDevice.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeContextLibrary.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeContextOS.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeContextNetwork.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeContextScreen.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ContextPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeContextReferrer {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContext {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextApp {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextDevice {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextLibrary {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextOS {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextNetwork {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextScreen {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ContextPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ContextPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ContextPigeonCodecWriter(data: data)
  }
}

class ContextPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ContextPigeonCodec(readerWriter: ContextPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeContextApi {
  func getContext(collectDeviceId: Bool, completion: @escaping (Result<NativeContext, Error>) -> Void)
  func clearReferrer() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeContextApiSetup {
  static var codec: FlutterStandardMessageCodec { ContextPigeonCodec.shared }
  /// Sets up an instance of `NativeContextApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeContextApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getContextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.segment_analytics.NativeContextApi.getContext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let collectDeviceIdArg = args[0] as! Bool
        api.getContext(collectDeviceId: collectDeviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContextChannel.setMessageHandler(nil)
    }
    let clearReferrerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.segment_analytics.NativeContextApi.clearReferrer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearReferrerChannel.setMessageHandler { _, reply in
        do {
          try api.clearReferrer()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearReferrerChannel.setMessageHandler(nil)
    }
  }
}
